backend:
  name: github
  repo: Marcholio/gatsby-netlify
media_folder: static/assets
public_folder: /assets
collections:
  - name: jumbo
    folder: markdown/jumbo
    label: Jumbo
    create: true
    fields:
      - { name: header, label: Header }
      - { name: description, label: Description }
